import type { SidebarState, StudioPreset } from "../types";

export const DEFAULT_SIDEBAR_STATE: SidebarState = {
  "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
  "id": "layout-instance",
  "tabIndex": 0,
  "width": 280,
  "height": 360,
  "gap": 16,
  "padding": 28,
  "margin": 0,
  "radius": 24,
  "borderWidth": 1,
  "borderStyle": "solid",
  "fontBucket": "google",
  "fontSearch": "",
  "systemFontIdx": 9,
  "googleFontFamily": "Inter",
  "fontSizeUnit": "px",
  "fontStyle": "normal",
  "textTransform": "none",
  "textDecoration": "none",
  "letterSpacing": 0,
  "letterSpacingUnit": "px",
  "lineHeight": 1.5,
  "radiusLinked": true,
  "radiusTL": 22,
  "radiusTR": 22,
  "radiusBR": 22,
  "radiusBL": 22,
  "shadowEnabled": true,
  "shadowX": 0,
  "shadowY": 8,
  "shadowBlur": 24,
  "shadowSpread": 0,
  "shadowOpacity": 0.25,
  "shadowColor": "#000000",
  "focusRingEnabled": true,
  "focusRingWidth": 2,
  "focusRingOffset": 2,
  "focusRingColor": "#38bdf8",
  "transitionDuration": 200,
  "transitionEasing": "ease",
  "background": "#0f172a",
  "foreground": "#e5eefb",
  "muted": "#94a3b8",
  "accent": "#38bdf8",
  "border": "#334155",
  "titleSize": 24,
  "bodySize": 15,
  "fontWeight": 700,
  "previewState": "default",
  "disabled": false,
  "disabledOpacity": 0.5,
  "disabledCursor": "not-allowed",
  "disabledUseCustomColors": false,
  "disabledBg": "#374151",
  "disabledText": "#9ca3af",
  "disabledBorder": "#4b5563",
  "title": "Workspace sidebar",
  "element": "aside",
  "role": "navigation",
  "landmarkLabel": "Workspace navigation",
  "side": "left",
  "railWidth": 76,
  "collapsed": false,
  "nestedGroups": 3,
  "itemCount": 8
};

export const SIDEBAR_PRESETS: StudioPreset[] = [
  {
    "id": "premium-glass-compact",
    "family": "premium",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "premium",
      "glass",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 24,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "disabledText": "#9ca3af",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "premium-glass-spacious",
    "family": "premium",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "premium",
      "glass",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 24,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "disabledText": "#9ca3af",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "premium-soft-compact",
    "family": "premium",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "premium",
      "soft",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 30,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "disabledText": "#9ca3af",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "premium-soft-spacious",
    "family": "premium",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "premium",
      "soft",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 30,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "disabledText": "#9ca3af",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "premium-crisp-compact",
    "family": "premium",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "premium",
      "crisp",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 12,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "disabledText": "#9ca3af",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "premium-crisp-spacious",
    "family": "premium",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "premium",
      "crisp",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 12,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "disabledText": "#9ca3af",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "premium-hero-compact",
    "family": "premium",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "premium",
      "hero",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 34,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "disabledText": "#9ca3af",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "premium-hero-spacious",
    "family": "premium",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "premium",
      "hero",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 34,
      "borderWidth": 1,
      "background": "#0f172a",
      "foreground": "#e5eefb",
      "disabledText": "#9ca3af",
      "muted": "#94a3b8",
      "accent": "#38bdf8",
      "border": "#334155",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "editorial-glass-compact",
    "family": "editorial",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "editorial",
      "glass",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 24,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "disabledText": "#9ca3af",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "editorial-glass-spacious",
    "family": "editorial",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "editorial",
      "glass",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 24,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "disabledText": "#9ca3af",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "editorial-soft-compact",
    "family": "editorial",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "editorial",
      "soft",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 30,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "disabledText": "#9ca3af",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "editorial-soft-spacious",
    "family": "editorial",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "editorial",
      "soft",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 30,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "disabledText": "#9ca3af",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "editorial-crisp-compact",
    "family": "editorial",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "editorial",
      "crisp",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 12,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "disabledText": "#9ca3af",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "editorial-crisp-spacious",
    "family": "editorial",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "editorial",
      "crisp",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 12,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "disabledText": "#9ca3af",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "editorial-hero-compact",
    "family": "editorial",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "editorial",
      "hero",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 34,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "disabledText": "#9ca3af",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "editorial-hero-spacious",
    "family": "editorial",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "editorial",
      "hero",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 34,
      "borderWidth": 1,
      "background": "#f8fafc",
      "foreground": "#0f172a",
      "disabledText": "#9ca3af",
      "muted": "#475569",
      "accent": "#f59e0b",
      "border": "#cbd5e1",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "admin-glass-compact",
    "family": "admin",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "admin",
      "glass",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 24,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "disabledText": "#9ca3af",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "admin-glass-spacious",
    "family": "admin",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "admin",
      "glass",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 24,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "disabledText": "#9ca3af",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "admin-soft-compact",
    "family": "admin",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "admin",
      "soft",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 30,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "disabledText": "#9ca3af",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "admin-soft-spacious",
    "family": "admin",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "admin",
      "soft",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 30,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "disabledText": "#9ca3af",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "admin-crisp-compact",
    "family": "admin",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "admin",
      "crisp",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 12,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "disabledText": "#9ca3af",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "admin-crisp-spacious",
    "family": "admin",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "admin",
      "crisp",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 12,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "disabledText": "#9ca3af",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "admin-hero-compact",
    "family": "admin",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "admin",
      "hero",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 34,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "disabledText": "#9ca3af",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "admin-hero-spacious",
    "family": "admin",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "admin",
      "hero",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 34,
      "borderWidth": 1,
      "background": "#111827",
      "foreground": "#f9fafb",
      "disabledText": "#9ca3af",
      "muted": "#9ca3af",
      "accent": "#22c55e",
      "border": "#374151",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "commerce-glass-compact",
    "family": "commerce",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "commerce",
      "glass",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 24,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "disabledText": "#9ca3af",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "commerce-glass-spacious",
    "family": "commerce",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "commerce",
      "glass",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 24,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "disabledText": "#9ca3af",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "commerce-soft-compact",
    "family": "commerce",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "commerce",
      "soft",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 30,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "disabledText": "#9ca3af",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "commerce-soft-spacious",
    "family": "commerce",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "commerce",
      "soft",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 30,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "disabledText": "#9ca3af",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "commerce-crisp-compact",
    "family": "commerce",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "commerce",
      "crisp",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 12,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "disabledText": "#9ca3af",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "commerce-crisp-spacious",
    "family": "commerce",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "commerce",
      "crisp",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 12,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "disabledText": "#9ca3af",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "commerce-hero-compact",
    "family": "commerce",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "commerce",
      "hero",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 34,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "disabledText": "#9ca3af",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "commerce-hero-spacious",
    "family": "commerce",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "commerce",
      "hero",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 34,
      "borderWidth": 1,
      "background": "#1e1b4b",
      "foreground": "#fff7ed",
      "disabledText": "#9ca3af",
      "muted": "#fbcfe8",
      "accent": "#fb7185",
      "border": "#4338ca",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "support-glass-compact",
    "family": "support",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "support",
      "glass",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 24,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "disabledText": "#9ca3af",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "support-glass-spacious",
    "family": "support",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "support",
      "glass",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 24,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "disabledText": "#9ca3af",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "support-soft-compact",
    "family": "support",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "support",
      "soft",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 30,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "disabledText": "#9ca3af",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "support-soft-spacious",
    "family": "support",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "support",
      "soft",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 30,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "disabledText": "#9ca3af",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "support-crisp-compact",
    "family": "support",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "support",
      "crisp",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 12,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "disabledText": "#9ca3af",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "support-crisp-spacious",
    "family": "support",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "support",
      "crisp",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 12,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "disabledText": "#9ca3af",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "support-hero-compact",
    "family": "support",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "support",
      "hero",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 34,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "disabledText": "#9ca3af",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "support-hero-spacious",
    "family": "support",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "support",
      "hero",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 34,
      "borderWidth": 1,
      "background": "#042f2e",
      "foreground": "#ccfbf1",
      "disabledText": "#9ca3af",
      "muted": "#5eead4",
      "accent": "#2dd4bf",
      "border": "#0f766e",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "system-glass-compact",
    "family": "system",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "compact",
    "tags": [
      "system",
      "glass",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 24,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "disabledText": "#9ca3af",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "system-glass-spacious",
    "family": "system",
    "archetype": "SaaS",
    "variant": "glass",
    "size": "spacious",
    "tags": [
      "system",
      "glass",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 24,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "disabledText": "#9ca3af",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "system-soft-compact",
    "family": "system",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "compact",
    "tags": [
      "system",
      "soft",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 30,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "disabledText": "#9ca3af",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "system-soft-spacious",
    "family": "system",
    "archetype": "Editorial",
    "variant": "soft",
    "size": "spacious",
    "tags": [
      "system",
      "soft",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 30,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "disabledText": "#9ca3af",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "system-crisp-compact",
    "family": "system",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "compact",
    "tags": [
      "system",
      "crisp",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 12,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "disabledText": "#9ca3af",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "system-crisp-spacious",
    "family": "system",
    "archetype": "Admin",
    "variant": "crisp",
    "size": "spacious",
    "tags": [
      "system",
      "crisp",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 12,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "disabledText": "#9ca3af",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "system-hero-compact",
    "family": "system",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "compact",
    "tags": [
      "system",
      "hero",
      "compact",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 560,
      "height": 240,
      "gap": 8,
      "padding": 16,
      "margin": 0,
      "radius": 34,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "disabledText": "#9ca3af",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  },
  {
    "id": "system-hero-spacious",
    "family": "system",
    "archetype": "Commerce",
    "variant": "hero",
    "size": "spacious",
    "tags": [
      "system",
      "hero",
      "spacious",
      "layout",
      "export-safe"
    ],
    "state": {
      "description": "Button-canon layout studio with native structure, responsive sizing, spacing, surface, and accessibility controls.",
      "id": "layout-instance",
      "tabIndex": 0,
      "width": 820,
      "height": 420,
      "gap": 22,
      "padding": 34,
      "margin": 0,
      "radius": 34,
      "borderWidth": 1,
      "background": "#18181b",
      "foreground": "#fafafa",
      "disabledText": "#9ca3af",
      "muted": "#a1a1aa",
      "accent": "#a78bfa",
      "border": "#3f3f46",
      "titleSize": 24,
      "bodySize": 15,
      "fontWeight": 700,
      "previewState": "default",
      "title": "Workspace sidebar",
      "element": "aside",
      "role": "navigation",
      "landmarkLabel": "Workspace navigation",
      "side": "left",
      "railWidth": 76,
      "collapsed": false,
      "nestedGroups": 3,
      "itemCount": 8
    }
  }
];
