import type { SidebarState } from "../types";

export type ExportPayload = { fileName: string; mimeType: "text/plain;charset=utf-8"; content: string };

export function buildExportPayload(state: SidebarState, fileName = "sidebar") : ExportPayload {
  return { fileName: `${fileName || "sidebar"}.jsx`, mimeType: "text/plain;charset=utf-8", content: buildReactCode(state) };
}

export function buildReactCode(state: SidebarState) {
  return [
    "import * as React from \"react\";",
    "",
    "const state = " + JSON.stringify(state, null, 2) + ";",
  "",
  "function resolveFont(s) { return s.fontBucket === \"google\" ? '\"' + s.googleFontFamily + '\", sans-serif' : \"inherit\"; }",
  "function buildShadow(s) { if (!s.shadowEnabled) return \"none\"; var hex = Math.round(s.shadowOpacity * 255).toString(16).padStart(2, \"0\"); return s.shadowX + \"px \" + s.shadowY + \"px \" + s.shadowBlur + \"px \" + s.shadowSpread + \"px \" + s.shadowColor + hex; }",
    "",
    "export default function SidebarComponent() {",
    "  const collapsed = state.collapsed || state.previewState === \"collapsed\";",
    "  const groupCount = Math.max(1, state.nestedGroups);",
    "  const items = Array.from({ length: state.itemCount }, (_, index) => `Item ${index + 1}`);",
    "  const groups = Array.from({ length: groupCount }, (_, index) => ({",
    "    title: `Group ${index + 1}`,",
    "    items: items.filter((_, itemIndex) => itemIndex % groupCount === index),",
    "  }));",
    "  const [hoveredKey, setHoveredKey] = React.useState(null);",
    "  const style = {",
    "    width: collapsed ? state.railWidth : state.width,",
    "    minHeight: state.height,",
    "    padding: collapsed ? Math.max(10, Math.round(state.padding * 0.55)) : state.padding,",
    "    margin: state.margin,",
    "    gap: state.gap,",
    "    borderRadius: state.radius,",
    "    border: `${state.borderWidth}px ${state.borderStyle} ${state.disabled && state.disabledUseCustomColors ? state.disabledBorder : state.border}`,",
    "        boxShadow: buildShadow(state),",
    "    background: state.background,",
    "    color: state.foreground,",
    "    fontFamily: resolveFont(state),",
    "    cursor: state.disabled ? state.disabledCursor : undefined,",
    "    marginLeft: state.side === \"right\" ? \"auto\" : state.margin,",
    "    transition: state.motion ? \"all 180ms ease\" : undefined,",
    "  };",
    "",
    "  return (",
    "    <aside id={state.id} aria-label={state.landmarkLabel} tabIndex={state.tabIndex} style={style}>",
    "      <div style={{ display: \"flex\", alignItems: \"center\", justifyContent: \"space-between\", gap: state.gap }}>",
    "        <a href=\"#\" style={{ color: state.foreground, fontSize: collapsed ? state.bodySize : state.titleSize, fontWeight: state.fontWeight, textDecoration: \"none\" }}>{collapsed ? state.title.slice(0, 1) : state.title}</a>",
    "        <button type=\"button\" aria-expanded={!collapsed} style={{ border: `1px solid ${state.border}`, borderRadius: 999, padding: \"4px 8px\", color: state.collapseIconColor, background: \"transparent\" }}>{collapsed ? \"Open\" : \"Collapse\"}</button>",
    "      </div>",
    "      {!collapsed && <p style={{ color: state.muted, fontSize: state.bodySize, marginTop: Math.max(8, state.gap / 2) }}>{state.description}</p>}",
    "      <nav aria-label={`${state.landmarkLabel} groups`} style={{ display: \"grid\", gap: state.gap, marginTop: state.gap, maxHeight: \"100%\", overflowY: \"auto\", scrollbarColor: `${state.scrollbarThumb} ${state.scrollbarBg}` }}>",
    "        {groups.map((group, groupIndex) => (",
    "          <section key={group.title} aria-labelledby={`${state.id}-group-${groupIndex}`} style={{ display: \"grid\", gap: Math.max(6, state.gap / 2) }}>",
    "            {groupIndex > 0 && <div aria-hidden=\"true\" style={{ height: 1, background: state.groupDividerColor, marginBottom: Math.max(6, state.gap / 2) }} />}",
    "            <button id={`${state.id}-group-${groupIndex}`} type=\"button\" aria-expanded={groupIndex === 0 || state.previewState !== \"overflow\"} style={{ border: 0, borderRadius: 12, padding: \"8px 12px\", textAlign: \"left\", color: state.groupHeaderColor, background: \"rgba(255,255,255,.04)\", textTransform: \"uppercase\", letterSpacing: \".16em\", fontSize: 12, fontWeight: 700 }}>{collapsed ? groupIndex + 1 : group.title}</button>",
    "            {(groupIndex === 0 || state.previewState !== \"overflow\") && group.items.map((item, itemIndex) => {",
    "              const active = groupIndex === 0 && itemIndex === 0;",
    "              const key = groupIndex + \"-\" + itemIndex;",
    "              const isHovered = hoveredKey === key || (state.previewState === \"hover\" && groupIndex === 0 && itemIndex === 0);",
    "              const showBadge = groupIndex === 0 && itemIndex === 1;",
    "              return (",
    "                <a key={item} href=\"#\" aria-current={active ? \"page\" : undefined} style={{ display: \"flex\", alignItems: \"center\", justifyContent: \"space-between\", borderRadius: 12, padding: \"8px 12px\", color: active ? state.activeItemText : isHovered ? state.hoverItemText : state.muted, background: active ? state.activeItemBg : isHovered ? state.hoverItemBg : \"transparent\", border: `1px solid ${active ? state.activeItemBorder : \"transparent\"}`, outline: state.previewState === \"focus\" && active ? `2px solid ${state.accent}` : undefined, outlineOffset: 3, textAlign: collapsed ? \"center\" : \"left\", textDecoration: \"none\" }} onMouseEnter={() => setHoveredKey(key)} onMouseLeave={() => setHoveredKey((current) => (current === key ? null : current))}>",
    "                  <span>{collapsed ? item.replace(\"Item \", \"\") : item}</span>",
    "                  {!collapsed && showBadge && <span aria-hidden=\"true\" style={{ minWidth: 18, height: 18, padding: \"0 5px\", display: \"grid\", placeItems: \"center\", borderRadius: 999, fontSize: 10, fontWeight: 700, background: state.badgeCountBg, color: state.badgeCountText }}>3</span>}",
    "                </a>",
    "              );",
    "            })}",
    "          </section>",
    "        ))}",
    "      </nav>",
    "    </aside>",
    "  );",
    "}",
    "",
  ].join("\n");
}
